AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VersionNumberParameter:
    Type: String
    Description: Version number of build

  S3BucketForCodeParameter:
    Type: String
    Description: S3 Bucket where code is located

  S3BucketPathForCodeParameter:
    Type: String
    Description: Path to code inside of bucket.  Include the zip filename, but do not include a leading backslash.

  S3BucketPathForStaticFilesParameter:
    Type: String
    Description: Path to static files inside of bucket.  Do not include a leading backslash.

  S3BucketPathForBlogImagesParameter:
    Type: String
    Description: Path to blog images folder inside of bucket.  Do not include a leading backslash.
    Default: demo_blogimages

  StageParameter:
    Type: String
    Description: Stage (environment)
    Default: dev

  DynamoDbTableBlogArticlesParameter:
    Type: String
    Description: Name of the DynamoDB table for blog articles
    Default: demo-articles

  DynamoDbTableUsersParameter:
    Type: String
    Description: Name of the DynamoDB table for users
    Default: dev-users

  DomainNameParameter:
    Type: String
    Description: Custom Domain Name (e.g., www.jamesqmurphy.com).  Leave blank if not mapping to a custom URL.
    Default: ''

  WarmUrlParameter:
    Type: String
    Description: URL for CloudWatch to call to keep Lambda function warm
    Default: '/warm'

  CertificateArnParameter:
    Type: String
    Description: Certificate ARN.  Leave blank if not mapping to a custom URL.
    Default: ''

  AppNameParameter:
    Type: String
    Description: 'Name of app to use in descriptions, etc.'
    Default: JamesQMurphyWeb

  ApiGatewayStageNameParameter:
    Type: String
    Description: Name to use for the API Gateway Stage
    Default: website


Conditions:
   AreMappingToCustomDomain: !Not [!Equals [!Ref DomainNameParameter, '']]
   AreWarmingTheLambda: !Not [!Equals [!Ref WarmUrlParameter, '']]

Resources:

  TheRoleForTheLambdaFunction:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudwatchWriteOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'
        - PolicyName: !Sub DynamoDbReadOnlyAccess-${DynamoDbTableBlogArticlesParameter}
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dynamodb:BatchGetItem'
                  - 'dynamodb:Describe*'
                  - 'dynamodb:List*'
                  - 'dynamodb:GetItem'
                  - 'dynamodb:Query'
                  - 'dynamodb:Scan'
                Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableBlogArticlesParameter}'


  TheRoleForTheApiGateway:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: CloudwatchWriteOnlyAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: '*'


  TheLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3BucketForCodeParameter
        S3Key: !Ref S3BucketPathForCodeParameter
      Description: !Sub Hosts ${AppNameParameter}-${VersionNumberParameter} ${StageParameter} ASP.NET Core application.  Created via CloudFormation stack ${AWS::StackName}.
      # Lambda does not allow periods in function names, so to include the version number,
      # we need to replace the periods with something else (hyphens in this case)
      FunctionName: !Join
        - '-'
        - - !Ref AppNameParameter
            # These !Select functions parse out the pieces of the version number
          - !Select [0, !Split [".", !Ref VersionNumberParameter]]
          - !Select [1, !Split [".", !Sub '${VersionNumberParameter}.' ]]
          - !Select [2, !Split [".", !Sub '${VersionNumberParameter}..' ]]
          - !Select [3, !Split [".", !Sub '${VersionNumberParameter}...' ]]
          - !Select [4, !Split [".", !Sub '${VersionNumberParameter}....' ]]
          - !Ref StageParameter
      Handler: JamesQMurphy.Web::JamesQMurphy.Web.LambdaEntryPoint::FunctionHandlerAsync
      MemorySize: 512
      Role: !GetAtt TheRoleForTheLambdaFunction.Arn
      Runtime: provided  # custom runtime
      Timeout: 15
      Environment:
        Variables:
          ImageBasePath: /blogimages
          WarmUrl: !Ref WarmUrlParameter
          ArticleStore__Service: DynamoDb
          ArticleStore__DynamoDbTableName: !Ref DynamoDbTableBlogArticlesParameter
      Tags:
        - Key: app
          Value: !Ref AppNameParameter
        - Key: version
          Value: !Ref VersionNumberParameter


  TheScheduledRuleToWarmTheLambda: 
    Type: AWS::Events::Rule
	Condition: AreWarmingTheLambda
    Properties: 
      Description: Calls the Lambda function every 5 minutes to keep it warm
      ScheduleExpression: "rate(5 minutes)"
      State: "ENABLED"
      Targets: 
        - Arn: !GetAtt TheLambdaFunction.Arn
          Id: TheLambdaToWarm
          Input: !Sub '{"httpMethod":"GET","path":"${WarmUrlParameter}"}'


  TheLambdaInvokePermissionForEvents: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref TheLambdaFunction
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt TheScheduledRuleToWarmTheLambda.Arn


  TheGatewayRestAPI:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub ${AppNameParameter}-${VersionNumberParameter}-${StageParameter}
      Description: !Sub ${AppNameParameter}-${VersionNumberParameter} ${StageParameter}. Created via CloudFormation stack ${AWS::StackName}.
      BinaryMediaTypes:
        - '*/*'
      EndpointConfiguration:
        Types:
          - REGIONAL


  TheRootGetMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TheLambdaFunction.Arn}/invocations
      ResourceId: !GetAtt TheGatewayRestAPI.RootResourceId
      RestApiId: !Ref TheGatewayRestAPI


  TheProxyResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref TheGatewayRestAPI
      ParentId: !GetAtt TheGatewayRestAPI.RootResourceId
      PathPart: '{proxy+}'


  TheProxyAnyMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref TheGatewayRestAPI
      ResourceId: !Ref TheProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TheLambdaFunction.Arn}/invocations


  TheDistResourceStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketForCodeParameter}.s3.amazonaws.com/${S3BucketPathForStaticFilesParameter}/cf-apiGatewayToS3.yaml'
      TimeoutInMinutes: 10
      Parameters:
        RestApiIdParameter: !Ref TheGatewayRestAPI
        ParentResourceIdParameter: !GetAtt TheGatewayRestAPI.RootResourceId
        ApiResourceNameParameter: dist
        S3BucketPathParameter: !Sub '${S3BucketForCodeParameter}/${S3BucketPathForStaticFilesParameter}/dist'


  TheBlogImagesResourceStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketForCodeParameter}.s3.amazonaws.com/${S3BucketPathForStaticFilesParameter}/cf-apiGatewayToS3.yaml'
      TimeoutInMinutes: 10
      Parameters:
        RestApiIdParameter: !Ref TheGatewayRestAPI
        ParentResourceIdParameter: !GetAtt TheGatewayRestAPI.RootResourceId
        ApiResourceNameParameter: blogimages
        S3BucketPathParameter: !Sub '${S3BucketForCodeParameter}/${S3BucketPathForBlogImagesParameter}'


  TheImagesResourceStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://${S3BucketForCodeParameter}.s3.amazonaws.com/${S3BucketPathForStaticFilesParameter}/cf-apiGatewayToS3.yaml'
      TimeoutInMinutes: 10
      Parameters:
        RestApiIdParameter: !Ref TheGatewayRestAPI
        ParentResourceIdParameter: !GetAtt TheGatewayRestAPI.RootResourceId
        ApiResourceNameParameter: images
        S3BucketPathParameter: !Sub '${S3BucketForCodeParameter}/${S3BucketPathForStaticFilesParameter}/images'


  TheDeploymentStage:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - TheRootGetMethod
      - TheProxyAnyMethod
      - TheDistResourceStack
      - TheBlogImagesResourceStack
      - TheImagesResourceStack
    Properties:
      Description: !Sub ${AppNameParameter}-${VersionNumberParameter} ${StageParameter}.  Created via CloudFormation stack ${AWS::StackName}.
      RestApiId: !Ref TheGatewayRestAPI
      StageName: !Ref ApiGatewayStageNameParameter


  TheLambdaInvokePermissionForProxyResource:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt TheLambdaFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${TheGatewayRestAPI}*


  TheCustomDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Condition: AreMappingToCustomDomain
    Properties:
      DomainName: !Ref DomainNameParameter
      RegionalCertificateArn: !Ref CertificateArnParameter
      EndpointConfiguration:
        Types:
          - REGIONAL


  TheBasePathMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    Condition: AreMappingToCustomDomain
    DependsOn:
      - TheDeploymentStage
    Properties:
      DomainName: !Ref TheCustomDomainName
      RestApiId: !Ref TheGatewayRestAPI
      Stage: !Ref ApiGatewayStageNameParameter


Outputs:
  GatewayApiUrl:
    Description: The Url to the Gateway API
    Value: !Sub https://${TheGatewayRestAPI}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${ApiGatewayStageNameParameter}

  SiteUrl:
    Description: The Url to the site
    Value: !Sub https://${DomainNameParameter}
    Condition: AreMappingToCustomDomain

  TargetDomainName:
    Description: Target domain name for DNS mapping
    Value: !GetAtt TheCustomDomainName.RegionalDomainName
    Condition: AreMappingToCustomDomain
