name: Trying GitHub Actions

on:
  push:
    branches: 
      - master
      - features/try-github-actions
      - features/try-github-actions-*

env:
  VERSION_MAJOR: 0
  VERSION_MINOR: 2
  VERSION_PATCH: 24
  BUILD_BUILDNUMBER: 0.2.24.0
# BUILD_BUILDNUMBER: ${{ format('{{{0}.{1}.{2}.{3}}}', env.VERSION_MAJOR, env.VERSION_MINOR, env.VERSION_PATCH, 0) }}
  JQM_COMPAREBRANCH: features/try-github-actions
  JQM_VERSIONFILE: .github/workflows/build.yml


jobs:
  build:
    env:
      BUILDCONFIGURATION: 'Release'
      JQM_PACKAGENAME: ${{ format('JamesQMurphy.Web.{0}.zip', jobs.build.env.BUILD_BUILDNUMBER ) }}
#     JQM_PACKAGENAME: JamesQMurphy.Web.0.2.22.0.zip
      JQM_ARTIFACTFOLDER: a
      JQM_CLOUDFORMATIONFILENAME: '*.yaml'
      JQM_TOOLINSTALLDIR: build/bin

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Validate build version
      run: pwsh $GITHUB_WORKSPACE/.github/workflows/validate-build-against-branch.ps1

    - name: Print environment variables
      run: printenv

    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install Amazon.Lambda.Tools --tool-path $JQM_TOOLINSTALLDIR

    - name: Run dotnet-lambda package
      run: ./dotnet-lambda package -c $BUILDCONFIGURATION -pl $GITHUB_WORKSPACE/src/JamesQMurphy.Web -o $GITHUB_WORKSPACE/$JQM_ARTIFACTFOLDER/$JQM_PACKAGENAME --msbuild-parameters "--self-contained true --runtime rhel-x64"
      working-directory: ${{ env.JQM_TOOLINSTALLDIR }}

    - name: Copy Cloudformation files
      run: cp deploy/$JQM_CLOUDFORMATIONFILENAME $GITHUB_WORKSPACE/$JQM_ARTIFACTFOLDER

    - name: Upload package 
      uses: actions/upload-artifact@master
      with:
        name: deploy
        path: ${{ env.JQM_ARTIFACTFOLDER }}

