name: .NET Core

on:
  push:
    branches: 
      - master
      - features/try-github-actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install Amazon.Lambda.Tools --tool-path build/bin

    - name: Run dotnet-lambda package
      run: ./dotnet-lambda package -c Release -pl src/JamesQMurphy.Web -o a/JamesQMurphy.Web --msbuild-parameters "--self-contained true --runtime rhel-x64"
      working-directory: build/bin
