name: .NET Core

on:
  push:
    branches: 
      - master
      - features/try-github-actions
      - features/try-github-actions-*

env:
  VERSION_MAJOR: 0
  VERSION_MINOR: 2
  VERSION_PATCH: 22
  BUILD_BUILDNUMBER: 0.2.22.0
# BUILD_BUILDNUMBER: ${{ format('{{{0}.{1}.{2}.{3}}}', env.VERSION_MAJOR, env.VERSION_MINOR, env.VERSION_PATCH, 0) }}
  JQM_COMPAREBRANCH: master
  JQM_VERSIONFILE: .github/build.yml


jobs:
  build:
    env:
      BUILDCONFIGURATION: 'Release'
#     JQM_PACKAGENAME: ${{ format('JamesQMurphy.Web.{0}.zip', '{{ env.BUILD_BUILDNUMBER }}') }}
      JQM_PACKAGENAME: JamesQMurphy.Web.0.2.22.0.zip
      JQM_ARTIFACTFOLDER: a
      JQM_CLOUDFORMATIONFILENAME: '*.yaml'
      JQM_TOOLINSTALLDIR: build/bin

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Action
      uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Validate build version
      run: $GITHUB_WORKSPACE/.github/validate-build-against-branch.ps1 -CompareBranch $JQM_COMPAREBRANCH -VersionFile $JQM_VERSIONFILE
      shell: pwsh

    - name: Print environment variables
      run: printenv

    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install Amazon.Lambda.Tools --tool-path $JQM_TOOLINSTALLDIR

    - name: Run dotnet-lambda package
      run: ./dotnet-lambda package -c $BUILDCONFIGURATION -pl $GITHUB_WORKSPACE/src/JamesQMurphy.Web -o $GITHUB_WORKSPACE/$JQM_ARTIFACTFOLDER/$JQM_PACKAGENAME --msbuild-parameters "--self-contained true --runtime rhel-x64"
      working-directory: ${{ env.JQM_TOOLINSTALLDIR }}

    - name: Upload artifact 
      uses: actions/upload-artifact@master
      with:
        name: ${{ env.JQM_PACKAGENAME }}
        path: ${{ env.JQM_ARTIFACTFOLDER }}

